2022-08-30 19:25:49,131  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:49,446  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:49,738  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:50,089  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:50,438  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:50,826  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:51,129  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-30 19:25:51,422  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb,debian-installer/s390-netdevice' package [parser.py]
2022-08-30 20:17:42,621  ERROR  No file found for 'loda' [downloader.py]
2022-08-30 20:21:25,420  ERROR  Invalid value for architecture [cmdline_parser.py]
2022-08-30 20:21:25,535  ERROR  No file found for '12' [downloader.py]
2022-08-30 20:22:05,079  ERROR  TypeError: Invalid value for architecture [cmdline_parser.py]
2022-08-30 20:22:11,014  ERROR  TypeError: Invalid value for architecture [cmdline_parser.py]
2022-08-30 20:22:11,193  ERROR  No file found for '12' [downloader.py]
2022-08-30 20:22:43,074  ERROR  TypeError: Invalid value for architecture [cmdline_parser.py]
2022-08-30 20:23:04,881  ERROR  No file found for 'alpha' [downloader.py]
2022-08-30 20:24:15,889  ERROR  No download file found for architecture 'alpha' [downloader.py]
2022-08-30 20:24:37,306  ERROR  No download file found for architecture 'alpha' at http://ftp.uk.debian.org/debian/dists/stable/main/ [downloader.py]
2022-08-30 20:30:29,011  ERROR  TypeError: Invalid value for architecture [cmdline_parser.py]
2022-08-31 00:09:01,472  ERROR  Cannot Connect: http://ftp.uk.debian.org/debian/dists/stable/main/ HTTPConnectionPool(host='ftp.uk.debian.org', port=80): Max retries exceeded with url: /debian/dists/stable/main/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10897ab30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) [downloader.py]
2022-08-31 01:08:45,819  ERROR  Problem encountered: None Invalid URL 'None': No scheme supplied. Perhaps you meant http://None? [downloader.py]
2022-08-31 08:46:35,354  ERROR  Problem encountered: Contents-amd64.gz Invalid URL 'Contents-amd64.gz': No scheme supplied. Perhaps you meant http://Contents-amd64.gz? [downloader.py]
2022-08-31 08:52:38,862  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,008  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,143  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,303  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,473  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,672  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,834  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb' package [parser.py]
2022-08-31 08:52:39,964  WARNING  No file for 'debian-installer/libgdk-pixbuf2.0-0-udeb,debian-installer/s390-netdevice' package [parser.py]
2022-08-31 08:53:56,231  ERROR  TypeError: Invalid value for architecture [cmdline_parser.py]
2022-08-31 10:47:26,273  ERROR  TypeError: Invalid value for architecture [cmdline_parser.py]
